# Practice Problems
### Lecture 7
Answer each number in a separate cell

Rename this notebook with your last name and the lecture 
 
 ex. Cych_B_07
    
Turn-in this notebook on Canvas.  

1. Generate arrays
    - Use **NumPy** to generate an array of integers ranging from 0 up to 360 by intervals of 10.
    - Use **NumPy** to generate an array from 0 to 2$\pi$ with 36 values (use the **NumPy** attribute **pi**)
    - print them both out. 
    - Use **NumPy** to generate an array with 20 equally spaced floating point numbers between 0 and 2$\pi$ and print it out.  
2. Array slicing
    - Load the data file _Datasets/RecentEarthquakes/earthquakeLocations.txt_ into a **NumPy** array. Remember that the folder _Datasets_ is in the  directory above the one that this notebook is in!  The data file contains the latitude and longitude of 10 different earthquakes.
    - Print out the shape of the array you just imported 
    - Convert the shape of the array to 2x10.  Use both the **.reshape()** and **.transpose()** methods. 
    - Print the shape of the two new arrays
    - Take a slice of only the latitudes and assign it in a new variable **lats**
    - Take a slice of only the longitudes and assign it in a new variable **lons**. 
    - Print the type of the variable **lats** and **lons**
    - Convert the new arrays, **lats** and **lons**, into separate lists and assign them to new variable names
    - Print the type of these two new variables
    - Save the numpy array **lats** into a text file labeled 'lats.txt'


Resources:

http://ds.iris.edu/ieb/index.html?format=text&nodata=404&starttime=1970-01-01&endtime=2025-01-01&minmag=0&maxmag=10&mindepth=0&maxdepth=900&orderby=time-desc&limit=1000&maxlat=89.18&minlat=-89.18&maxlon=180.00&minlon=-180.00&zm=1&mt=ter) 

In [7]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

myints1 = np.arange(0,361,10)
print (myints1)

[  0  10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170
 180 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350
 360]


In [8]:
myvals = np.linspace(0, np.pi*2,36)
myvals

array([0.        , 0.17951958, 0.35903916, 0.53855874, 0.71807832,
       0.8975979 , 1.07711748, 1.25663706, 1.43615664, 1.61567622,
       1.7951958 , 1.97471538, 2.15423496, 2.33375454, 2.51327412,
       2.6927937 , 2.87231328, 3.05183286, 3.23135244, 3.41087202,
       3.5903916 , 3.76991118, 3.94943076, 4.12895034, 4.30846992,
       4.48798951, 4.66750909, 4.84702867, 5.02654825, 5.20606783,
       5.38558741, 5.56510699, 5.74462657, 5.92414615, 6.10366573,
       6.28318531])

In [9]:
myvals2 = np.linspace(0,2*np.pi,20)
myvals2

array([0.        , 0.33069396, 0.66138793, 0.99208189, 1.32277585,
       1.65346982, 1.98416378, 2.31485774, 2.64555171, 2.97624567,
       3.30693964, 3.6376336 , 3.96832756, 4.29902153, 4.62971549,
       4.96040945, 5.29110342, 5.62179738, 5.95249134, 6.28318531])

In [10]:
import numpy as np

EQ = np.loadtxt("../Datasets/RecentEarthquakes/earthquakeLocations.txt")
EQ.shape
print (EQ)

(10, 2)

[[  66.07 -149.03]
 [  38.83 -122.8 ]
 [  32.92 -115.47]
 [  47.63 -122.51]
 [  60.97 -151.24]
 [  37.65 -118.85]
 [  53.2  -161.3 ]
 [  19.41 -155.28]
 [  38.84 -122.83]
 [  36.88  -89.12]]


In [15]:
newEQ = EQ.reshape(2,10)
print (newEQ)

[[  66.07 -149.03   38.83 -122.8    32.92 -115.47   47.63 -122.51   60.97
  -151.24]
 [  37.65 -118.85   53.2  -161.3    19.41 -155.28   38.84 -122.83   36.88
   -89.12]]


In [6]:
EQ.transpose()

array([[  66.07,   38.83,   32.92,   47.63,   60.97,   37.65,   53.2 ,
          19.41,   38.84,   36.88],
       [-149.03, -122.8 , -115.47, -122.51, -151.24, -118.85, -161.3 ,
        -155.28, -122.83,  -89.12]])

In [35]:
lats = EQ[:,0]
lons = EQ[:,1]
print(lats)
print (lons)

[66.07 38.83 32.92 47.63 60.97 37.65 53.2  19.41 38.84 36.88]
[-149.03 -122.8  -115.47 -122.51 -151.24 -118.85 -161.3  -155.28 -122.83
  -89.12]


In [42]:
listlats = list(lats)
listlons = list(lons)
print (listlats, "\n\n",listlons)

[66.07, 38.83, 32.92, 47.63, 60.97, 37.65, 53.2, 19.41, 38.84, 36.88] 

 [-149.03, -122.8, -115.47, -122.51, -151.24, -118.85, -161.3, -155.28, -122.83, -89.12]


In [43]:
np.savetxt("lats.txt", listlats)

In [2]:
%pycat lats.txt

In [4]:
! curl https://lance-modis.eosdis.nasa.gov/imagery/gallery/2012270-0926/Miriam.A2012270.2050.2km.jpg

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   162  100   162    0     0    224      0 --:--:-- --:--:-- --:--:--   224
